### ISSUE TITLE
Trying to load ExamplePlugin gives "Invalid plugin manifest!"

### ISSUE THREAD

**Issue by Inrixia** [uwu/neptune-template#1]
![image](https://github.com/uwu/neptune-template/assets/6373693/d77ed0b6-8335-40cc-b5f3-f01dff5040df)

See title. After building the `ExamplePlugin` and then attempting to load it via the file regardless of using the `manifest.json` or `index.js` in the dist directory I receive the above error.

**Comment by twnlink** [comment]
neptune supports two methods of plugin loading, 1 is via a remote URL, the other is via a local file. To use a local file, prepend your JS file with a comment containing the manifest.json, e.g 
```javascript
/*
{
  "name": "whatever",
  "etc": "etc"
}
*/

// plugin code here
```
Local plugins DO NOT support multi-file plugin loading (as in, importing code from other files) unless you use a bundler.

I personally use the http-server npm package and the plugin reload button in neptune to test my plugins. If you do use this method, note that you must pass `--cors` to http-server to get it to work properly.

**Comment by Inrixia** [comment]
Sweet this works thanks!

**Comment by Inrixia** [comment]
Seems I can no longer load plugins to test using http-server as tidal now requires certs to be valid on web requests?

**Comment by twnlink** [comment]
I'm trying to see if I can find an Electron setting for this, but if not I may end up polyfilling `fetch` in plugins to use node-fetch.

**Comment by Inrixia** [comment]
I'm already doing that here https://github.com/Inrixia/neptune-plugins/blob/master/lib/fetchy.js To get around the builtin cors limitations etc.

Though it uses https not fetch since its builtin.

**Comment by twnlink** [comment]
I've since fixed this issue, please give it a moment and then reinstall neptune using the installer.

**Comment by Inrixia** [comment]
Sweet, I just self signed a dev cert lol, but if I end up testing again without it Ill lyk if it breaks :)
