### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Inrixia** [uwu/neptune-template#2]
Without documentation its hard to know the full capabilities of what can be done within a Neptune plugin plus it looks like modules which only exist at runtime within the Neptune client are being imported like `@neptune/store`, supporting typescript would help avoid errors and make it easier to work with the interfaces provided.

Is there any plan to support typescript?

**Comment by twnlink** [comment]
The specific issue is that every API available on both @neptune/store and @neptune/actions are automatically fetched from TIDAL's untyped bundle. To provide TypeScript support I would need to manually type an ever-changing API surface. You can use Redux DevTools in the Chrome inspector, as well as looking at window.neptune.actions to get a good idea of how things work, but I can't provide type definitions.

I do intend on providing documentation in the future on neptune's own APIs as well as common development workflows, such as leveraging Redux DevTools.

**Comment by Inrixia** [comment]
It is possible to have TS support without using enums or literal types for the tidal api endpoints allowing for type safety except for unknown endpoints. That combined with documentation I think would be the best approach and would only require type updates when Neptune's api changes.

**Comment by twnlink** [comment]
@Inrixia The default plugin template now has type definitions, you can install them with `pnpm install --save-dev neptune-types`.

**Comment by Inrixia** [comment]
Awesome thanks! Will I will need to update the plugin build process to support TS?

**Comment by twnlink** [comment]
> Awesome thanks! Will I will need to update the plugin build process to support TS?

You should be able to just change the file extension to ts and update the manifest file. Please note that the types are slightly incomplete at the moment (I think) but most of if not all of TIDAL's own APIs are typed.

**Comment by Inrixia** [comment]
This is great! Thanks again

**Comment by Inrixia** [comment]
Fully ported to TS now! Thanks for the help
