### ISSUE TITLE
GitHub Pages Deployment

### ISSUE THREAD

**Issue by Inrixia** [uwu/neptune-template#3]
I'm trying to get https://github.com/Inrixia/neptune-plugins working with github pages. The workflow works fine but there is no indication of where on pages its hosted. I've tried going to https://inrixia.github.io/neptune-plugins/TidalTags but that's not working

**Comment by twnlink** [comment]
You may have to enable GitHub pages in your repo settings. There should also be a gh-pages branch that should show you the file structure of the site.

**Comment by Inrixia** [comment]
I've tried enabling pages but still not working. Its fine though I'm just using the github raw urls instead.

Not sure why pages isnt working through, could you share what repo settings you have for yours?

**Comment by twnlink** [comment]
I'll show you when I get home, just to keep you updated :)

**Comment by Inrixia** [comment]
No rush thanks for the help

**Comment by twnlink** [comment]
<img width="821" alt="image" src="https://github.com/uwu/neptune-template/assets/31049082/1677f527-ce46-4ac1-8a9d-f18d9d9264b2">
